<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SprintSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Table sprint
        DB::table('sprint')->insert([
        [ // Sprint 1 Project 1
            'nama' => 'Sprint 1',
            'project_id' => 1,
            'tanggal_mulai' => Carbon::create('2020', '11', '01'),
            'tanggal_akhir' => Carbon::create('2020', '11', '07'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 1
            'nama' => 'Sprint 2',
            'project_id' => 1,
            'tanggal_mulai' => Carbon::create('2020', '11', '08'),
            'tanggal_akhir' => Carbon::create('2020', '11', '14'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 1
            'nama' => 'Sprint 3',
            'project_id' => 1,
            'tanggal_mulai' => Carbon::create('2020', '11', '15'),
            'tanggal_akhir' => Carbon::create('2020', '11', '21'),
            'status' => 'Proses',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 1
            'nama' => 'Sprint 4',
            'project_id' => 1,
            'tanggal_mulai' => Carbon::create('2020', '11', '22'),
            'tanggal_akhir' => Carbon::create('2020', '11', '28'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 2
            'nama' => 'Sprint 1',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '10', '04'),
            'tanggal_akhir' => Carbon::create('2020', '10', '10'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 2
            'nama' => 'Sprint 2',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '10', '11'),
            'tanggal_akhir' => Carbon::create('2020', '10', '17'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 2
            'nama' => 'Sprint 3',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '10', '18'),
            'tanggal_akhir' => Carbon::create('2020', '10', '24'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 2
            'nama' => 'Sprint 4',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '10', '25'),
            'tanggal_akhir' => Carbon::create('2020', '10', '31'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 5 Project 2
            'nama' => 'Sprint 5',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '10', '01'),
            'tanggal_akhir' => Carbon::create('2020', '10', '07'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 6 Project 2
            'nama' => 'Sprint 6',
            'project_id' => 2,
            'tanggal_mulai' => Carbon::create('2020', '02', '08'),
            'tanggal_akhir' => Carbon::create('2020', '02', '14'), 
            'status' => 'Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 3
            'nama' => 'Sprint 1',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '08'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 3
            'nama' => 'Sprint 2',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '01', '11'),
            'tanggal_akhir' => Carbon::create('2021', '01', '15'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 3
            'nama' => 'Sprint 3',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '01', '18'),
            'tanggal_akhir' => Carbon::create('2021', '01', '22'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 3
            'nama' => 'Sprint 4',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '01', '25'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 5 Project 3
            'nama' => 'Sprint 5',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '02', '01'),
            'tanggal_akhir' => Carbon::create('2021', '02', '05'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 6 Project 3
            'nama' => 'Sprint 6',
            'project_id' => 3,
            'tanggal_mulai' => Carbon::create('2021', '02', '08'),
            'tanggal_akhir' => Carbon::create('2021', '02', '12'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 4
            'nama' => 'Sprint 1',
            'project_id' => 4,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '08'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 4
            'nama' => 'Sprint 2',
            'project_id' => 4,
            'tanggal_mulai' => Carbon::create('2021', '01', '11'),
            'tanggal_akhir' => Carbon::create('2021', '01', '15'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 4
            'nama' => 'Sprint 3',
            'project_id' => 4,
            'tanggal_mulai' => Carbon::create('2021', '01', '18'),
            'tanggal_akhir' => Carbon::create('2021', '01', '22'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 4
            'nama' => 'Sprint 4',
            'project_id' => 4,
            'tanggal_mulai' => Carbon::create('2021', '01', '25'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 6
            'nama' => 'Sprint 1',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 6
            'nama' => 'Sprint 2',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '02', '01'),
            'tanggal_akhir' => Carbon::create('2021', '02', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 6
            'nama' => 'Sprint 3',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '03', '01'),
            'tanggal_akhir' => Carbon::create('2021', '03', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 6
            'nama' => 'Sprint 4',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '04', '05'),
            'tanggal_akhir' => Carbon::create('2021', '04', '30'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 5 Project 6
            'nama' => 'Sprint 5',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '05', '03'),
            'tanggal_akhir' => Carbon::create('2021', '05', '28'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 6 Project 6
            'nama' => 'Sprint 6',
            'project_id' => 6,
            'tanggal_mulai' => Carbon::create('2021', '06', '01'),
            'tanggal_akhir' => Carbon::create('2021', '06', '30'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 7
            'nama' => 'Sprint 1',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 7
            'nama' => 'Sprint 2',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '02', '01'),
            'tanggal_akhir' => Carbon::create('2021', '02', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 7
            'nama' => 'Sprint 3',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '03', '01'),
            'tanggal_akhir' => Carbon::create('2021', '03', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 7
            'nama' => 'Sprint 4',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '04', '05'),
            'tanggal_akhir' => Carbon::create('2021', '04', '30'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 5 Project 7
            'nama' => 'Sprint 5',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '05', '03'),
            'tanggal_akhir' => Carbon::create('2021', '05', '28'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 6 Project 7
            'nama' => 'Sprint 6',
            'project_id' => 7,
            'tanggal_mulai' => Carbon::create('2021', '06', '01'),
            'tanggal_akhir' => Carbon::create('2021', '06', '30'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 8
            'nama' => 'Sprint 1',
            'project_id' => 8,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 8
            'nama' => 'Sprint 2',
            'project_id' => 8,
            'tanggal_mulai' => Carbon::create('2021', '02', '01'),
            'tanggal_akhir' => Carbon::create('2021', '02', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 3 Project 8
            'nama' => 'Sprint 3',
            'project_id' => 8,
            'tanggal_mulai' => Carbon::create('2021', '03', '01'),
            'tanggal_akhir' => Carbon::create('2021', '03', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],[ // Sprint 4 Project 8
            'nama' => 'Sprint 4',
            'project_id' => 8,
            'tanggal_mulai' => Carbon::create('2021', '04', '05'),
            'tanggal_akhir' => Carbon::create('2021', '04', '30'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        
        [ // Sprint 1 Project 9
            'nama' => 'Sprint 1',
            'project_id' => 9,
            'tanggal_mulai' => Carbon::create('2021', '01', '04'),
            'tanggal_akhir' => Carbon::create('2021', '01', '29'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),    
        ],[ // Sprint 2 Project 9
            'nama' => 'Sprint 2',
            'project_id' => 9,
            'tanggal_mulai' => Carbon::create('2021', '02', '01'),
            'tanggal_akhir' => Carbon::create('2021', '02', '26'), 
            'status' => 'Belum',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ]]);
    }
}
